[gdrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0Ad52N3-Ukl6v0wNk9hJOKOI5N8IqGVoMOnPPPGgD_79soiJLNVsEp12wbKFxUZLKM3yhlviMXMU2qA4DBr56QeRs6vD68htYaUC4HLr59RF4sJWEGk6DR7AUN1UbFciy3j792AV1aC1GYIJ-rtkpZ-aU-THTgF2So-vdaCgYKARESARESFQHGX2MiTrJKjVpuHjz9LFnT74YBMg0171","token_type":"Bearer","refresh_token":"1//03fB4uj_jSxbSCgYIARAAGAMSNwF-L9IrISxbhlQIM8BqMOokW6b9Wz-moiWBIZtF7sqngoP7hPbvGgnIIFFh2jojWOoPalciLso","expiry":"2024-04-03T13:53:03.931947582+01:00"}
team_drive = 

