[FileDialog]
history=file:///home/dolphin/Music/Davide Van de Sfroos, file:///home/dolphin/University/Modules/Ethical Hacking/Assignment_1, file:///home/dolphin/VirtualBox VMs, file:///home/dolphin/Media/OSs, file:///home/dolphin/Downloads
lastVisited=file:///home/dolphin/Media/OSs
qtVersion=5.15.10
shortcuts=file:, file:///home/dolphin
sidebarWidth=87
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd1\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)"
viewMode=Detail
