set $MediumOrchid #BA55D3
set $w95 #008080

set $main-color $MediumOrchid

font FiraCode Medium 12
seat seat0 xcursor_theme phinger-cursors-light 32

# Inner gaps for all windows: space between two adjacent windows (or split containers).
# gaps inner <gap_size>[px]
gaps inner 0px

# Outer gaps for all windows: space along the screen edges.
# gaps outer|horizontal|vertical|top|left|bottom|right <gap_size>[px]
gaps bottom 0px

# Inner and outer gaps for all windows on a specific workspace.
# <ws> can be a workspace number or name.
# workspace <ws> gaps inner <gap_size>[px]
# workspace <ws> gaps outer|horizontal|vertical|top|left|bottom|right <gap_size>[px]

# Enabling “Smart Gaps” means no gaps will be shown when there is
# precisely one window or split container on the workspace.
#
# inverse_outer only enables outer gaps when there is exactly one
# window or split container on the workspace.
# smart_gaps on|off|inverse_outer

smart_gaps off
default_border pixel 2
default_floating_border normal
titlebar_padding 1
titlebar_border_thickness 0

# class                 border  	backgr. 		text    	indicator 		child_border
client.focused          $main-color $main-color 	#ffffff 	$main-color 	$main-color
client.focused_inactive #333333 	#5f676a 		#ffffff 	#484e50   		#5f676a
client.unfocused        #333333 	#222222 		#888888 	#292d2e   		#222222
client.urgent           #2f343a 	$main-color 	#ffffff 	$main-color   	$main-color
client.placeholder      #000000 	#0c0c0c 		#ffffff 	#000000   		#0c0c0c

# Start swaybar to display a workspace bar (plus the system information i3status
# finds out, if available)
#exec swaync &
bar {
		swaybar_command waybar
		hidden_state hide
		mode dock
		gaps 0
		position top
        status_command i3status
        tray_bindsym button2 ContextMenu
        icon_theme Tela-green
		colors {
			background #000000
			separator #ffffff
			statusline #ffffff
			focused_workspace #AA55AA #AA55AA #ffffff
			inactive_workspace #000000 #000000 #ffffff
			active_workspace #626262 #000000 #ffffff
			urgent_workspace #faa41a #8C3333 #ffffff
		}       
}
